language: python
python:
  - "3.6"

services:
  - docker

before_script: pip install docker-compose

script:
  - ci_env="bash <(curl -s https://codecov.io/env)"
  - ci_post_cov="bash <(curl -s https://codecov.io/bash)"

  # Run backend tests (Python) and upload coverage.
  - docker-compose run backend sh -c '$ci_env && pytest --cov=dreambox --cov-report xml && $ci_post_cov'

  # Run frontend tests (JavaScript) and upload coverage.
  - docker-compose run frontend sh -c "$ci_env && yarn test:coverage && $ci_post_cov"
