version: "3"
services:
  dreambox-frontend:
    restart: always
    build: ./frontend
    volumes:
      - image-uploads:/uploads

  dreambox-backend:
    restart: always
    build: ./backend
    volumes:
      - image-uploads:/uploads

  database:
    restart: always
    image: redis

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - dreambox-backend
      - dreambox-frontend
    networks:
      default:
        aliases:
          - dreambox.com
          - api.dreambox.com
          - dreambox-backend
    volumes:
      - image-uploads:/uploads

volumes:
  image-uploads:
