version: "3"
services:
  dreamdrugs-frontend:
    environment:
      - NODE_ENV=production

  dreamdrugs-backend:
    environment:
      - ENV=production
      - DEBUG=0
      - FLASKPORT=4000
      - GUNICORNPORT=8000
