version: "3"
services:
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - image-uploads:/uploads

  backend:
    restart: always
    build: ./backend
    volumes:
      - image-uploads:/uploads

  database:
    restart: always
    image: redis

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    networks:
      default:
        aliases:
          - dreambox.com
          - api.dreambox.com
    volumes:
      - image-uploads:/uploads

volumes:
  image-uploads:
