version: "3"
services:
  frontend:
    restart: always
    build: ./frontend
    volumes:
      - image-uploads:/uploads
      - ./frontend:/dreamdrugs/frontend
      - /dreamdrugs/frontend/node_modules
    environment:
      - NODE_ENV=development
      - BACKEND_DOMAIN=backend
      - REDIS_HOST=database

  backend:
    restart: always
    build: ./backend
    volumes:
      - image-uploads:/uploads
      - ./backend:/dreamdrugs/backend
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - FLASKPORT=8000
      - REDIS_HOST=database

  database:
    restart: always
    image: redis

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    volumes:
      - image-uploads:/uploads

volumes:
  image-uploads:
