version: "3"
services:
  frontend:
    restart: always
    build: ./frontend
    expose:
      - "3000"
    volumes:
      - image-uploads:/uploads

  backend:
    restart: always
    build: ./backend
    expose:
      - "8000"
    volumes:
      - image-uploads:/uploads

  nginx:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    links:
      - backend
      - frontend
    networks:
      default:
        aliases:
          - dreambox.com
          - api.dreambox.com
    volumes:
      - image-uploads:/uploads

volumes:
  image-uploads:
