version: "3"
services:
  dreamdrugs-frontend:
    volumes:
      - ./frontend:/dreamdrugs/frontend
      - /dreamdrugs/frontend/node_modules
    environment:
      - NODE_ENV=development

  dreamdrugs-backend:
    volumes:
      - ./backend:/dreamdrugs/backend
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
      - DEBUG=1
      - FLASKPORT=8000
