apiVersion: skaffold/v1
kind: Config
metadata:
  name: dreamdrugs
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/dreamdrugs/backend
    context: backend
  - image: gcr.io/dreamdrugs/frontend
    context: frontend
deploy:
  helm:
    flags:
      upgrade:
      - "--install"  # https://github.com/GoogleContainerTools/skaffold/issues/2142#issuecomment-553835849
    releases:
    - name: skaffold-helm
      chartPath: deploy/dreamdrugs
      setValues:
        backendImage: gcr.io/dreamdrugs/backend
        frontendImage: gcr.io/dreamdrugs/frontend
        development: true
