apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-backend
  labels:
    app: {{ template "dreamdrugs.fullname" . }}-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ template "dreamdrugs.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ template "dreamdrugs.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backendImage }}
          env:
          - name: ENV
            value: 'production'
          - name: DEBUG
            value: '0'
          - name: FLASKPORT
            value: '4000'
          - name: GUNICORNPORT
            value: '8000'
          - name: REDIS_HOST
            value: 'redis-master.default.svc.cluster.local'
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis
                key: redis-password
          ports:
          - containerPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-backend
spec:
  type: NodePort
  selector:
    app: {{ template "dreamdrugs.fullname" . }}-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
