apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-frontend
  labels:
    app: {{ template "dreamdrugs.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "dreamdrugs.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "dreamdrugs.fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontendImage }}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: 'production'
        - name: BACKEND_DOMAIN
          value: {{ template "dreamdrugs.fullname" . }}-backend
        - name: REDIS_HOST
          value: 'redis-master.default.svc.cluster.local'
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password

---
kind: Service
apiVersion: v1
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-frontend
spec:
  type: NodePort
  selector:
    app: {{ template "dreamdrugs.fullname" . }}-frontend
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3000
