apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-nginx
  labels:
    app: {{ template "dreamdrugs.fullname" . }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ template "dreamdrugs.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ template "dreamdrugs.fullname" . }}-nginx
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: nginx:1.15.3-alpine
        name: nginx
        ports:
        - name: http
          containerPort: {{ .Values.hostPort }}
          hostPort: {{ .Values.hostPort }}
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx"
      volumes:
      - name: config
        configMap:
          name: {{ template "dreamdrugs.fullname" . }}-nginx-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "dreamdrugs.fullname" . }}-nginx-conf
data:
  nginx.conf: |
    worker_processes 1;
    error_log /dev/stdout info;

    events {
      worker_connections 10;
    }

    http {
      access_log /dev/stdout;

      server {
        listen {{ .Values.hostPort }};
        location /api {
          proxy_pass http://{{ template "dreamdrugs.fullname" . }}-backend:6000/;
        }
        location / {
          # Configuration needed for socket.io to work.
          #
          #     https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/
          #
          # TODO: Move this to specific route since right now the frontend server
          # handles the React application serving plus the socket serving.
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_http_version 1.1;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   Host            $host;

          proxy_pass http://{{ template "dreamdrugs.fullname" . }}-frontend:3030/;
        }
      }
    }
