apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    deployment: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: backend
  template:
    metadata:
      labels:
        pod: backend
    spec:
      containers:
        - name: backend
          image: docker.pkg.github.com/docwhite/dreambox/backend:1.0.0
          env:
            - name: ENV
              value: 'production'
            - name: DEBUG
              value: '0'
            - name: FLASKPORT
              value: '4000'
            - name: GUNICORNPORT
              value: '8000'
      imagePullSecrets:
        - name: regcred
