name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Run backend tests
      run: docker-compose run dreambox-backend sh -c 'pytest --cov=dreambox --cov-report xml'

    - name: Run frontend tests
      run: docker-compose run dreambox-frontend sh -c 'yarn test:coverage'

    - name: Upload test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
