name: Deploy

on:
  push:
    tags:
      - '*'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: dreamdrugs

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract release version from tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Debug release version
      run: echo $RELEASE_VERSION

    - name: Setup Google Cloud Platform credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    - name: Configure docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build backend
      run: |
        docker \
          build \
          -t gcr.io/"$GKE_PROJECT"/backend:"$RELEASE_VERSION" \
          -t gcr.io/"$GKE_PROJECT"/backend:"$GITHUB_SHA" \
          ./backend

    - name: Build frontend
      run: |
        docker \
          build \
          -t gcr.io/"$GKE_PROJECT"/frontend:"$RELEASE_VERSION" \
          -t gcr.io/"$GKE_PROJECT"/frontend:"$GITHUB_SHA" \
          ./frontend

    - name: Push backend container
      run: |
        docker push gcr.io/$GKE_PROJECT/backend:"$RELEASE_VERSION"
        docker push gcr.io/"$GKE_PROJECT"/backend:"$GITHUB_SHA"

    - name: Push frontend container
      run: |
        docker push gcr.io/$GKE_PROJECT/frontend:"$RELEASE_VERSION"
        docker push gcr.io/"$GKE_PROJECT"/frontend:"$GITHUB_SHA"

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh

        echo Adding stable repository.
        helm repo add stable https://kubernetes-charts.storage.googleapis.com/

    - name: Install dependant charts
      run: helm dependency update deploy/dreamdrugs

    - name: Deploy
      run: |
        gcloud container clusters \
          get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $GKE_PROJECT

        sed -i 's/version: .*/version: '"$RELEASE_VERSION"'/' deploy/dreamdrugs/Chart.yaml
        sed -i 's/appVersion: .*/appVersion: '"$RELEASE_VERSION"'/' deploy/dreamdrugs/Chart.yaml

        echo Deploying it all to GKE.
        helm upgrade --install dreamdrugs deploy/dreamdrugs \
          --set backendImage=gcr.io/"$GKE_PROJECT"/backend:"$GITHUB_SHA" \
          --set frontendImage=gcr.io/"$GKE_PROJECT"/frontend:"$GITHUB_SHA" \
          --set redis.master.persistence=false \
          --set redis.slave.persistence=false \
          --set redis.password=$REDIS_PASSWORD \
          --set cloudflare.email=$CLOUDFLARE_EMAIL \
          --set cloudflare.globalApiKey=$CLOUDFLARE_GLOBAL_API_KEY
