name: Deploy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract release version from tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Build backend
      run: docker-compose build backend

    - name: Build frontend
      run: docker-compose build frontend

    - name: Push backend container
      run: |
        docker login docker.pkg.github.com -u docwhite -p ${{ secrets.GITHUB_TOKEN }}
        docker tag dreambox_backend docker.pkg.github.com/docwhite/dreambox/backend:${{ env.RELEASE_VERSION }}
        docker push docker.pkg.github.com/docwhite/dreambox/backend:${{ env.RELEASE_VERSION }}

    - name: Push frontend container
      run: |
        docker login docker.pkg.github.com -u docwhite -p ${{ secrets.GITHUB_TOKEN }}
        docker tag dreambox_frontend docker.pkg.github.com/docwhite/dreambox/frontend:${{ env.RELEASE_VERSION }}
        docker push docker.pkg.github.com/docwhite/dreambox/frontend:${{ env.RELEASE_VERSION }}

    - name: Trigger deploy
      run: echo TODO deployment to Kubernetes on AWS
