name: Deploy

on:
  push:
    tags:
      - '*'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: dreambox

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish and Deploy.
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Extract release version from tag
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

    - name: Setup Google Cloud Platform credentials
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    - name: Configure docker to use gcloud command-line tool as a credential helper
      run: gcloud auth configure-docker

    - name: Build backend
      run: docker build -t gcr.io/"$GKE_PROJECT"/backend:${{ env.RELEASE_VERSION }} ./backend

    - name: Build frontend
      run: docker build -t gcr.io/"$GKE_PROJECT"/frontend:${{ env.RELEASE_VERSION }} ./frontend

    - name: Push backend container
      run: |
        docker push gcr.io/$GKE_PROJECT/backend:${{ env.RELEASE_VERSION }}

    - name: Push frontend container
      run: |
        docker push gcr.io/$GKE_PROJECT/frontend:${{ env.RELEASE_VERSION }}

    - name: Set up Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh
        ./get_helm.sh

    - name: Deploy
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        helm upgrade --install dreambox deploy/dreambox --set backendImage=gcr.io/"$GKE_PROJECT"/backend:${{ env.RELEASE_VERSION }} --set frontendImage=gcr.io/"$GKE_PROJECT"/frontend:${{ env.RELEASE_VERSION }}
        helm status dreambox
