name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build backend
      run: docker-compose build backend

    - name: Run backend tests
      run: docker-compose run backend sh -c 'pytest --cov=dreambox --cov-report xml'

    - name: Build frontend
      run: docker-compose build frontend

    - name: Run frontend tests
      run: docker-compose run frontend sh -c 'yarn test:coverage'

    - name: Upload test coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Push backend container
      run: |
        docker login docker.pkg.github.com -u docwhite -p ${{ secrets.GITHUB_TOKEN }}
        docker tag dreambox_frontend docker.pkg.github.com/docwhite/dreambox/backend:1.0
        docker push docker.pkg.github.com/docwhite/dreambox/backend:1.0

    - name: Push frontend container
      run: |
        docker login docker.pkg.github.com -u docwhite -p ${{ secrets.GITHUB_TOKEN }}
        docker tag dreambox_frontend docker.pkg.github.com/docwhite/dreambox/frontend:1.0
        docker push docker.pkg.github.com/docwhite/dreambox/frontend:1.0

    - name: Trigger deploy
      run: echo TODO deployment to Kubernetes on AWS
