apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA5lgGKTY7+sItsAhk0PNLi44n5zyQhREM275FLaMQzgVJU2AKoMuo6Uogmlkg5AL6c71GUnUdgpmzyrPZ8q9Q3tDDVgD8mVAV7gMySigCDSwaki+DwrmHPKOdzBGcuBmlbfy2mBQAu8nGic+8DTum3+WEQEUl4uApKEseqv1pqz/IBV11K+GRTSJHOkqx4+D2lM5F75qHDCZqL7Zc/2lTDzVrtKTLCL6Aqi5o154dU26TzKsoAdNaLO35cc5mFPnI7YlooMOiOVwA0uq24yzyeQH5xNbuWsBQHWR5PxIaxzSY//7qkaUhuLuHAfFS4hm0CieOG4Ke1hwA5J7fYwCEE2YX1BUWT4JirnVQyRwl5lbAwjD8hMKPnkV0GmNVq/atLcKY5u+6Ao13sieJeUXX61NgbZrUcW0MqUnkhilwPYApsTLAU6c21I9K04Ly2SVZJyFyZSuZyoD7A41XxxpgJcIrc4nr8YeMHSdIorQ2IYS7ky4GXriAsHY4NHBQThc9h1NUthlyXYCaZvS7QFMM9aeDOQxLypFsmvPDIpCmgnoPBmIGem+2G+MzFRNMy6wzGa97hsh6Vwp8GWwXJIQx1717I8AS4SQkpCrrhCICDZhIByLfF3CNruulVlXd0dDaYelWDQ1XKI2q5dTirc7l9esxxpzU7OtPYoAP5AE8OKkWdhWFfY5ziBM6s7zNIw7fX9YRhvzpuu1B/JgKFgERLgEBWwmRx2BPYm4yLAlZl9w7EKRF1ri6MG2yx2W4YMqnS0SlXDALqz42Rb5r9H5cHT107aOJ37fPN3+WDLliMRlXbBpdQNmwtYgAgUImW+g52ZteoQCgmrlnLORAwDGQ46ad2qtqmiePmgzscfe6fcqA7PLaT6keGBoFTDOAgPAKDCreIyqhRQ3UTNHAdQeasnr37L2ItQuQwssywhPkoBIFGJVEl4gd5z63qGXbCMENodo4Fc5PL/vWuPnI+bV653hQLD3OOOLUzO1kuPynyCTHD
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
status: {}

